version: "3"
services:
    apache:
        image: 'bitnami/apache:2.4.41-debian-10-r11'
        container_name: 'apache'
        ports:
            - '80:8080'
            - '443:8443'
        volumes:
            - "${SHARED_FOLDER_DIR}:/app"
            - ./docker-configs/apache/httpd.conf:/opt/bitnami/apache/conf/httpd.conf
            - ./docker-configs/apache/vhosts/:/vhosts/custom/
            - ./docker-configs/apache/certs:/certs
        networks:
            - webserver_network

    php-fpm-56:
        build: 
            context: ./docker-configs/php/5.6
            args:
                OCI8_INSTALL: ${OCI8_INSTALL}
        container_name: php-fpm-56
        working_dir: /app
        volumes:
            - "${SHARED_FOLDER_DIR}:/app"
            - ./docker-configs/php/5.6/php-fpm-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
            - ./docker-configs/php/5.6/php-cli-overrides.ini:/etc/php5/cli/conf.d/99-overrides.ini
        networks:
            - webserver_network
            - db_network
  
    php-fpm-72:
        build:
            context: ./docker-configs/php/7.2
            args:
                OCI8_INSTALL: ${OCI8_INSTALL}
        container_name: php-fpm-72
        working_dir: /app
        volumes:
            - "${SHARED_FOLDER_DIR}:/app"
            - ./docker-configs/php/7.2/php-fpm-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
            - ./docker-configs/php/7.2/php-cli-overrides.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
        networks:
            - webserver_network
            - db_network
            
    php-fpm-73:
        build:
            context: ./docker-configs/php/7.3
            args:
                OCI8_INSTALL: ${OCI8_INSTALL}
        container_name: php-fpm-73
        working_dir: /app
        volumes:
            - "${SHARED_FOLDER_DIR}:/app"
            - ./docker-configs/php/7.3/php-fpm-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
            - ./docker-configs/php/7.3/php-cli-overrides.ini:/etc/php/7.3/cli/conf.d/99-overrides.ini
        networks:
            - webserver_network
            - db_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
            - PMA_USER=${MYSQL_ROOT_USER}
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - UPLOAD_LIMIT=500000000
        networks:
            - webserver_network
            - db_network

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
        networks:
            - webserver_network

networks:
  webserver_network:
    driver: bridge
  db_network: 
    external:
        name: docker-mysql_db_network
